server:
  port: 8002

logging:
  level:
    org.taylor.nora.common.feign: debug

feign:
  sentinel:
    enabled: true
  client:
    config:
     default:
       connectTimeout: 5000
       readTimeout: 5000
