server:
  port: 9000
  servlet:
    session:
      cookie:
        name: CASTC
spring:
  redis:
    host: localhost
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
